[theme]
primaryColor = "#3498db"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[server]
port = 8080
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false 